image:
  name: traefik
  tag: "2.8.0"

providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true

additionalArguments:
  - "--certificatesresolvers.le-staging.acme.tlschallenge=true"
  - "--certificatesresolvers.le-staging.acme.email=willy@rjurado.com"
  - "--certificatesresolvers.le-staging.acme.storage=/data/acme.json"
  - "--certificatesresolvers.le-staging.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
  - "--certificatesresolvers.le.acme.tlschallenge=true"
  - "--certificatesresolvers.le.acme.email=willy@rjurado.com"
  - "--certificatesresolvers.le.acme.storage=/data/acme.json"

logs:
  access:
    enabled: true

# You can enable the persistence to store the ACME JSON file and avoid creating new certificates each time Traefik is restarted.
# However, depending on your Kubernetes distribution, it could block the helm upgrade operation and force you to uninstall and re-install Traefik.

# persistence:
#   enabled: true
#   name: data
#   accessMode: ReadWriteOnce
#   size: 128Mi
#   path: /data